services:
  mongodb:
    image: mongo:6.0
    container_name: grovyn_mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secretpassword
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  #  NEW FASTAPI SERVICE
  api:
    build: . 
    container_name: grovyn_api
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    env_file:
      - .env  
    environment:
     
      - MONGO_URI=mongodb://admin:secretpassword@mongodb:27017/?authSource=admin

volumes:
  mongo_data: